[mypy]

disable_error_code = import-untyped

strict = True

plugins = numpy.typing.mypy_plugin

exclude = (^|/)(discord_interface|search|environment)/

[mypy-discord_interface.*]
ignore_errors = True

[mypy-rlgammon.search.*]
ignore_errors = True

[mypy-rlgammon.environment.*]
ignore_errors = True

[mypy-icga.old.*]
ignore_errors = True
